apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern-app
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9tYXliZXRocnVhbDE4MTA6UHJvamVjdDEyMw==  # base64-encoded connection string
